### ISSUE TITLE
water_x2 is not used in shader

### ISSUE THREAD

**Issue by capttheo** [Arnklit/WaterGenGodot#1]
First of all, great effect.
I was looking into shader and noticed you have water_x1 twice
`water_x1.b * .65 + water_x1.b * 0.35` in both foam and normal calculation
Guess it was meant to be mix of water_x1 and water_x2?

Also any tips to make water less repetitive and less jelly? Currently it loops in like half a second.

**Comment by Arnklit** [comment]
Ah well spotted! Thanks you. I've changed it now. it should be corrected a bit later when I do a commit.

I will work on fixing the repetitive "jelly" effect later, when I get around to doing more work on the shader. It's due to pulsing in between the flowmap with a constant frequency I think.

The issue is described on page 32 of this talk: https://steamcdn-a.akamaihd.net/apps/valve/2010/siggraph2010_vlachos_waterflow.pdf

**Comment by capttheo** [comment]
The second usage though (at line 60 NORMALMAP = ...) 😊

**Comment by Arnklit** [comment]
Oh dear, seems I did some serious copy pasta when I wrote that. Fixed that one as well, might be a little while before it gets committed since I'm in the middle of some other big changes.

**Comment by Arnklit** [comment]
I have implemented several fixes for the repeating patterns now. you can see the results a bit in this video. 
https://youtu.be/wi-3vFMwmME

I mostly just ended up using the solutions described here.
https://catlikecoding.com/unity/tutorials/flow/texture-distortion/
