### ISSUE TITLE
Why water shader type does not flow?

### ISSUE THREAD

**Issue by FrankLeeC** [Arnklit/WaterGenGodot#10]
Hi, i tested Waterways(V0.2.1) on MacOS with godot 3.2 stable version.
The river flows with lava shader type, but doesn't flow with water shader type.
https://github.com/Arnklit/WaterwaysDemo V0.2.1 works well in godot.

**Comment by Arnklit** [comment]
I think I'll need some more information on this. I cannot recreate this. It works fine for me.
Could you send me a small project where it doesn't work?

**Comment by FrankLeeC** [comment]
sorry about that.
here is my project.   https://github.com/FrankLeeC/TestWaterways

**Comment by FrankLeeC** [comment]
> I think I'll need some more information on this. I cannot recreate this. It works fine for me.
> Could you send me a small project where it doesn't work?


sorry about that.
here is my project. https://github.com/FrankLeeC/TestWaterways

**Comment by Arnklit** [comment]
Hmm strange. I'm not sure what's happened, but the normal map files have not been imported correctly. It's strange because if I create a new project and get the addon from the asset lib it imports them correctly, but opening your project they seemed to be stuck in some weird limbo where they weren't being read correctly.

Well simply open addons/waterways/textures and select water1_normal_bump.png. Go to the import tab and press reimport and the texture will work correctly. 

![image](https://user-images.githubusercontent.com/4955051/111919786-9e881780-8a83-11eb-923e-14160322ebb7.png)

**Comment by FrankLeeC** [comment]
> Hmm strange. I'm not sure what's happened, but the normal map files have not been imported correctly. It's strange because if I create a new project and get the addon from the asset lib it imports them correctly, but opening your project they seemed to be stuck in some weird limbo where they weren't being read correctly.
> 
> 
> 
> Well simply open addons/waterways/textures and select water1_normal_bump.png. Go to the import tab and press reimport and the texture will work correctly. 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/4955051/111919786-9e881780-8a83-11eb-923e-14160322ebb7.png)
> 
> 

THANKS! It works for me.👍
