### ISSUE TITLE
Feature Request: Albedo as gradient 

### ISSUE THREAD

**Issue by NHodgesVFX** [Arnklit/WaterGenGodot#5]
**Is your feature request related to a problem? Please describe.**
 making stylized water

**Describe the solution you'd like**
 I would like to change the color of the water with a gradient based on the depth. basically make albedo take a gradient instead of a color.

**Describe alternatives you've considered**
Writing is a custom shader is the only option I could think of.

**Comment by Arnklit** [comment]
Would you feel like a 2 colour gradient just going from one colour to another handles this well enough for you? That's what I'm learning towards in this, as I could make a clean interface for that, rather than having a full gradient resource to edit and it would be easier to pass the data to the shader.

**Comment by NHodgesVFX** [comment]
Yeah that should be good, I also like how this person applies the tint depth to the water https://www.youtube.com/watch?v=eKgNyDGvo7s would be cool to have that as a option to. not quite sure what they are doing though. the caustics are also a nice touch if your going for a clean water look. Sorry, just bombarding you with requests.

**Comment by Arnklit** [comment]
Now in master:

![image](https://user-images.githubusercontent.com/4955051/103314918-09452c00-4a1c-11eb-841d-e4d765a1bdd7.png)

![image](https://user-images.githubusercontent.com/4955051/103314945-182bde80-4a1c-11eb-9fc2-6e6a45f2cfd0.png)
