### ISSUE TITLE
Water shader does not work with an orthogonal camera

### ISSUE THREAD

**Issue by kelteseth** [Arnklit/WaterGenGodot#8]
**Describe the bug**
Buggy rendering in our Global Game Jam project: https://gitlab.com/kelteseth/globalgamejam2021

**To Reproduce**
1. Go to Camera and change it to orthogonal camera

**Expected behavior**
Water shader

**Screenshots**

![grafik](https://user-images.githubusercontent.com/1071536/106321140-2ddb3080-6274-11eb-838d-5dc953035635.png)
orthogonal camera:
![grafik](https://user-images.githubusercontent.com/1071536/106321168-359ad500-6274-11eb-845e-16b42b6b4e20.png)

**Environment**
- OS: Windows 10
- Graphics Vega VII
- Godot version 3.2.3
- Plugin version  most recent master
- Renderer used GLES3

Thanks! ❤

**Comment by Arnklit** [comment]
Hmm interesting, never tested it with the orthogonal cameras. I guess the depth tests I perform for the water are acting incorrectly in ortho.

I can have a look at this tomorrow morning and see if it's possible to make a variant of the shader that fixes this.

**Comment by Arnklit** [comment]
Turned out to be a pretty easy fix. The fix is in the dev branch.

Simply replace the *river.shader* file in your **addons/waterways/shaders** folder with this one:

https://github.com/Arnklit/Waterways/blob/dev/addons/waterways/shaders/river.shader

Or just replace your entire Waterways add-on folder with a copy of the add-on downloaded from the dev branch:

https://github.com/Arnklit/Waterways/tree/dev

If you could let me know if it works alright I would really appreciate it.

**Comment by kelteseth** [comment]
@Arnklit thanks works wonderful 🐱‍🏍✨✨✨
![grafik](https://user-images.githubusercontent.com/1071536/106354596-49d1e700-62f3-11eb-8d54-6545aa74f627.png)

**Comment by Arnklit** [comment]
Awesome. Your game looks amazing!
